[package]
name = "cru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "3.0.2"
dirs = "5.0.1"
git2 = "0.17.2"
